# @name postUserHappyPath
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "any-new-username-{{$timestamp}}",
  "name": "any-new-name-{{$timestamp}}",
  "password": "any-new-password-{{$timestamp}}"
}

###

# @name postBlogHappyPath
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "any-title-{{$timestamp}}",
  "author": "any-author-{{$timestamp}}",
  "url": "https://example.com",
  "likes": 8
}
###

# @name postBlogErrorTitleIsRequired
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "any-author-{{$timestamp}}",
  "url": "https://example.com",
  "likes": 8
}
###

# @name postBlogErrorUrlIsRequired
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "any-title-{{$timestamp}}",
  "author": "any-author-{{$timestamp}}",
  "likes": 8
}
###

# @name getAllBlogsHappyPath
GET http://localhost:3003/api/blogs
###

# @name getAllUsersHappyPath
GET http://localhost:3003/api/users
###

# @name getOneBlogHappyPath
GET http://localhost:3003/api/blogs/{{postBlogHappyPath.response.body.id}}
###

# @name getOneBlogWrongId
GET http://localhost:3003/api/blogs/hihihihi
###

# @name putBlogHappyPath
PUT http://localhost:3003/api/blogs/{{postBlogHappyPath.response.body.id}}
Content-Type: application/json

{
  "title": "{{postBlogHappyPath.response.body.title}}",
  "author": "{{postBlogHappyPath.response.body.author}}",
  "url": "https://example.com",
  "likes": 100
}
###

# @name deleteBlogHappyPath
DELETE http://localhost:3003/api/blogs/{{postBlogHappyPath.response.body.id}}
